class HandleLocalInfoUserDetail {
  final List<String> detail = [
    'Gualan, Zacapa Líder De Servicio, en Administración de Empresas con maestrías en Administración de Negocios y Administración de Proyectos y Liderazgo Organizacional, 30 años de experiencia, en Planeación Estratégica, Recursos Humanos, Finanzas, Costos, Presupuestos, Inventarios, Compras, Procesos, Políticas y procedimientos, Diseño, Elaboración y Evaluación de Proyectos, Investigación Social. Implementación de Programas Sociales y empresariales, implementación de Sistemas de Gestión (ISO 9000, SQF, HACCP, BASC, RSE).',
    'Experiencia de más de 5 años en la toma de requerimientos, análisis, documentación, desarrollo e implementaciones de aplicaciones web, móvil, web service y BI utilizando Java y sus frameworks, adicional a esto como gestión de equipos, proyectos, evaluación de costos y desarrollo tecnológico. Capacidad para abstraer diversas situaciones comerciales en informes, cubos de información, tablero, cuadro de mando y sistemas de soporte para decisiones ejecutivas.',
    'Desarrollos en: .Net, Java, php, qt, Oracle, mysql, sqlite, postgres, sql, c++, html, css, js, servidores linux / windows, crystal report, reporting services. Así mismo múltiples herramientas de BI, diagramas, bdd, virtualización hardware/software, modelado y pronóstico numérico, antenas satelitales.',
    'Software Architect en Asociación Guatemalteca de Exportadores - AGEXPORT Guatemala, Guatemala Analizar, diseñar, planificar y desarrollar soluciones escalables y mantenibles de software orientado a objetos y servicios, impulsar y promover la tecnología para alcanzar los objetivos institucionales, implementar y asegurar la calidad de los productos entregados, proporcionar soporte y mejoras a las soluciones existentes y brindar un excelente servicio al cliente o usuario final, trabajar con actitud positiva, integridad y profesionalidad para cumplir con las metas propuestas por la organización.',
    'Fiabilidad, mantenimiento y gestión de activos, gestión de proyectos y planificación estratégica Guatemala, Guatemala Ingeniero con experiencia en Gestión de Proyectos de Confiabilidad, Mantenimiento y Gestión de Activos en las Industrias de Petróleo y Gas, Minería, Metales e Industrias de Alimentos y Bebidas, también excelente desempeño como Gerente de Procura y Cadena de Suministro en la industria de Alimentos y Bebidas. Experto en planificación, estrategias de reducción de costos, presupuesto de mantenimiento e indicadores de desempeño, balances de carga, reducción de horas extras, optimización de recursos, desarrollo de alternativas de repuestos y proveedores, implementación de sistemas de gestión de mantenimiento y proyectos de mejora continua ',
    'Me especializo en la gestión de cambio. La implementación de nuevas metodologías en el área de manufactura de diferentes compañías me ha permitido desarrollar el liderazgo necesario para la transformación de equipos de trabajo orientada a procesos estandarizados. ',
    'Profesional de adquisiciones de alta gerencia innovador y orientado a resultados con más de 10 años de experiencia en bienes de consumo de embalaje (CPG), industria de fabricación y tecnología. MBA Graduado de INCAE Business School (Rango Nª1 BS en América Latina) participando de un programa de MBA Exchange Student en la Universidad de Michigan - Ross School of Business durante el otoño de 2014. Me apasiona el campo de la cadena de suministro y siempre estoy buscando nuevos desafíos relacionados que superen mis expectativas. Como profesional de la cadena de suministro, creo que mi trabajo es encontrar la "mejor" manera para que cualquier organización conecte productos (o servicios) con los clientes y desde los últimos 10 años lo he estado haciendo desde la perspectiva del abastecimiento estratégico.',
    'Licenciado en Administración de Empresas y Máster en Administración de la Confiabilidad. Profesional con más 10 años de experiencia liderando equipos multidisciplinarios, en el área Financiera, Logística, Importación y Exportación. ',
    ' Tengo experiencia, en reportar a casa matriz, también dándole seguimiento a los distribuidores en Guatemala y C.A., apoyándoles con estrategias de ventas, cobros, capacitaciones. He tendido la oportunidad de colocar productos desde cero, Estoy dispuesto a cambiarme de residencia si el puesto así lo requiere'
        'Profesional de la industria farmacéutica con seis años de experiencia, previamente como visitador médico y en la actualidad como Gerente de Mercadeo. Especialista en investigación de mercados, me he desarrollado en análisis de la competencia y estudio de precios, implementación de Marketing Estratégico y comunicación estratégica. Enfocado en lanzar productos altamente competitivos en el mercado tanto para canal privado como institucional. Negociación con proveedores internacionales. Experiencia desarrollando e implementado estrategias de venta, manejo de presupuesto y planificación y control de muestra médica.',
  ];
}
